#config ps4 untuk laptop
#check lagi dgn jstest /dev/input/jsX
mappings:
  axes:
    - axes[0] * -1.0 #LX
    - axes[1] * 1.0 #LY
    - axes[3] #RX
    - axes[4] * 1.0 #RY
    - (axes[2] - 1) * 0.5 #L2 
    - (axes[5] - 1) * 0.5 #R2
  
  buttons:
    - buttons[0] #silang
    - buttons[1] #bulat
    - buttons[2] #wajik
    - buttons[3] #kotak
    - buttons[4] #L1
    - buttons[5] #R1
    - buttons[6] #L2
    - buttons[7] #R2
    - buttons[8] #share
    - buttons[9] #options
    - buttons[10] #PS
    - buttons[11] #L3
    - buttons[12] #R3
    - min(axes[6], 0.0) * -1.0 #kiri [13]
    - max(axes[6], 0.0) #kanan       [14]
    - min(axes[7], 0.0) * -1.0 #atas  [15]
    - max(axes[7], 0.0) #bawah        [16]