ring_mri:
  - 3220  #type 1  
  - 3740  #type 2a
  - 4120  #type 3
  - 4080  #type 3
  - 4108  #type 2b

# x dan y banyak nya harus sama
sudut_y:
  - 32
  - 32
  - 32
  - 28  

sudut_x:
  - 0
  - 0
  - 0
  - 10

bldc_pwm_range:
  - 3000
  - 6000

bldc_offset:
  - 200
  - 450

boost_bldc_1:
  - 30
  - 20
  - 60 #3
  - 20 #3

boost_bldc_2: 
  - 100
  - 50
  - 200 #3
  - 100 #3
